### ISSUE TITLE
找遍全网也没找到第八版的，请问同学能分享一下吗？最好是英文原版的

### ISSUE THREAD

**Issue by wholon** [PEGASUS1993/Computer-Networking-A-Top-Down-Approach-8th-Edtion#1]

**Comment by PEGASUS1993** [comment]
> _No description provided._

老兄 参考PPT吧  因为这本书英文版今年才出版上市 市面上基本上没啥电子版的

**Comment by wholon** [comment]
> > _No description provided._
> 
> 老兄 参考PPT吧 因为这本书英文版今年才出版上市 市面上基本上没啥电子版的

好吧，谢谢
